spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 318749004191-1lo0r1omhkmfss1q1gqrfifnpdho7mpo.apps.googleusercontent.com
            clientSecret: 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
            scope: profile, email
  profiles:
    include: oauth
#spring.security.oauth2.client.registration.google.client-id=클라이언트 ID
#spring.security.oauth2.client.registration.google.client-secret=클라이언트 보안 비밀번호
#spring.security.oauth2.client.registration.google.scope=profile,email